# Generated by Django 3.2.11 on 2024-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_recordingdetail_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingdetail',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recordingdetail',
            name='height',
            field=models.PositiveIntegerField(),
        ),
    ]
